#!/usr/bin/env node

var program = require('commander')
  , fs = require('fs')
  , path = require('path')
  , predict = require('./index');

program
  .usage('<path/to/package.json> <path/to/X_.csv> <path/to/trace_.csv> <ISO 8601 date> [options]')
  .parse(process.argv);

if(program.args.length !== 4){
  console.error('\033[91mFAIL\033[0m: Invalid usage run: ssm predict <path/to/package.json> <path/to/X_.csv> <path/to/trace_.csv> <ISO 8601 date>');
  process.exit(1);
}

function resolvePath(string) {
  if (string.substr(0,1) === '~')
    string = process.env.HOME + string.substr(1)
  return path.resolve(string)
};

try {
  var theta = JSON.parse(fs.readFileSync(resolvePath(program.args[0])));
} catch (e){
  console.error('\033[91mFAIL\033[0m: ' + e.message);
  process.exit(1);  
}

var xPath = resolvePath(program.args[1])
  , tracePath = resolvePath(program.args[2])
  , date = program.args[3];

predict(date, xPath, tracePath, function(err, data){
  if(err){
    console.error('\033[91mFAIL\033[0m: ' + err.message);
    process.exit(1);  
  }

  var prediction = theta.resources.filter(function(x){return x.name === 'prediction'})[0];
  if(!prediction){
    theta.resources.push({name: "prediction", data: data});
  } else {
    prediction.data = data;
  }

  console.log(JSON.stringify(theta, null, 2));
});
